//package org.greenlist.entity;
//// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1
//
//import java.util.ArrayList;
//import java.util.Date;
//import java.util.List;
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToMany;
//import javax.persistence.ManyToOne;
//import javax.persistence.Table;
//import javax.persistence.Temporal;
//import javax.persistence.TemporalType;
//
///**
// * Coupon generated by hbm2java
// */
//@Entity
//@Table(name = "coupon", catalog = "projet3")
//public class Coupon implements java.io.Serializable {
//
//	private static final long serialVersionUID = 1L;
//	private int id;
//	private Admin admin;
//	private boolean ispublic;
//	private int valeur;
//	private Date dateDebutValidite;
//	private Date dateFinValidite;
//	private String code;
//	private List<Utilisateur> utilisateurs = new ArrayList<>();
//
//	public Coupon() {
//	}
//
//	public Coupon(int id, Admin admin, boolean ispublic, int valeur, Date dateDebutValidite, String code) {
//		this.id = id;
//		this.admin = admin;
//		this.ispublic = ispublic;
//		this.valeur = valeur;
//		this.dateDebutValidite = dateDebutValidite;
//		this.code = code;
//	}
//
//	public Coupon(int id, Admin admin, boolean ispublic, int valeur, Date dateDebutValidite, Date dateFinValidite,
//			String code, List<Utilisateur> utilisateurs) {
//		this.id = id;
//		this.admin = admin;
//		this.ispublic = ispublic;
//		this.valeur = valeur;
//		this.dateDebutValidite = dateDebutValidite;
//		this.dateFinValidite = dateFinValidite;
//		this.code = code;
//		this.utilisateurs = utilisateurs;
//	}
//
//	@Id
//	@GeneratedValue(strategy = GenerationType.IDENTITY)
//	@Column(name = "ID", unique = true, nullable = false)
//	public int getId() {
//		return this.id;
//	}
//
//	public void setId(int id) {
//		this.id = id;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "IDADMIN", nullable = false)
//	public Admin getAdmin() {
//		return this.admin;
//	}
//
//	public void setAdmin(Admin admin) {
//		this.admin = admin;
//	}
//
//	@Column(name = "ISPUBLIC", nullable = false)
//	public boolean isIspublic() {
//		return this.ispublic;
//	}
//
//	public void setIspublic(boolean ispublic) {
//		this.ispublic = ispublic;
//	}
//
//	@Column(name = "VALEUR", nullable = false)
//	public int getValeur() {
//		return this.valeur;
//	}
//
//	public void setValeur(int valeur) {
//		this.valeur = valeur;
//	}
//
//	@Temporal(TemporalType.DATE)
//	@Column(name = "DATE_DEBUT_VALIDITE", nullable = false, length = 10)
//	public Date getDateDebutValidite() {
//		return this.dateDebutValidite;
//	}
//
//	public void setDateDebutValidite(Date dateDebutValidite) {
//		this.dateDebutValidite = dateDebutValidite;
//	}
//
//	@Temporal(TemporalType.DATE)
//	@Column(name = "DATE_FIN_VALIDITE", length = 10)
//	public Date getDateFinValidite() {
//		return this.dateFinValidite;
//	}
//
//	public void setDateFinValidite(Date dateFinValidite) {
//		this.dateFinValidite = dateFinValidite;
//	}
//
//	@Column(name = "CODE", nullable = false, length = 10)
//	public String getCode() {
//		return this.code;
//	}
//
//	public void setCode(String code) {
//		this.code = code;
//	}
//
//	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "coupons")
//	public List<Utilisateur> getUtilisateurs() {
//		return this.utilisateurs;
//	}
//
//	public void setUtilisateurs(List<Utilisateur> utilisateurs) {
//		this.utilisateurs = utilisateurs;
//	}
//
//}
