package org.greenlist.entity;
// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Email generated by hbm2java
 */
@Entity
@Table(name = "email", catalog = "projet3")
public class Email implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private int id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDTYPE", nullable = false)
	private TypeEmail typeEmail;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUTILISATEUR", nullable = false)
	private Utilisateur utilisateur;
	@Column(name = "CONTENU", nullable = false, length = 10000)
	private String contenu;
	@Column(name = "OBJET", nullable = false, length = 250)
	private String objet;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_EMISSION", nullable = false, length = 19)
	private Date dateEmission;

	public Email() {
	}

	public Email(int id, TypeEmail typeEmail, Utilisateur utilisateur, String contenu, String objet,
			Date dateEmission) {
		this.id = id;
		this.typeEmail = typeEmail;
		this.utilisateur = utilisateur;
		this.contenu = contenu;
		this.objet = objet;
		this.dateEmission = dateEmission;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public TypeEmail getTypeEmail() {
		return this.typeEmail;
	}

	public void setTypeEmail(TypeEmail typeEmail) {
		this.typeEmail = typeEmail;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public String getContenu() {
		return this.contenu;
	}

	public void setContenu(String contenu) {
		this.contenu = contenu;
	}

	public String getObjet() {
		return this.objet;
	}

	public void setObjet(String objet) {
		this.objet = objet;
	}

	public Date getDateEmission() {
		return this.dateEmission;
	}

	public void setDateEmission(Date dateEmission) {
		this.dateEmission = dateEmission;
	}

}
