package org.greenlist.entity;
// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Experience generated by hbm2java
 */
@Entity
@Table(name = "experience", catalog = "projet3")
public class Experience implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private int id;
	@Column(name = "EXPERIENCE", nullable = false, length = 100)
	private String experience;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "experience")
	private List<Utilisateur> utilisateurs = new ArrayList<>();

	public Experience() {
	}

	public Experience(int id, String experience) {
		this.id = id;
		this.experience = experience;
	}

	public Experience(int id, String experience, List<Utilisateur> utilisateurs) {
		this.id = id;
		this.experience = experience;
		this.utilisateurs = utilisateurs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getExperience() {
		return this.experience;
	}

	public void setExperience(String experience) {
		this.experience = experience;
	}

	public List<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(List<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
