package org.greenlist.entity;
// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "projet3")
public class Message implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private int id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDECHANGE", nullable = false)
	private Echange echange;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDTICKET", nullable = false)
	private Ticket ticket;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUTILISATEUR", nullable = false)
	private Utilisateur utilisateur;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_ENVOI", nullable = false, length = 19)
	private Date dateEnvoi;
	@Column(name = "CORPS", nullable = false, length = 10000)
	private String corps;
	@Column(name = "ISLU", nullable = false)
	private boolean islu;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "message")
	private List<Ticket> tickets = new ArrayList<>();

	public Message() {
	}

	public Message(int id, Echange echange, Ticket ticket, Utilisateur utilisateur, Date dateEnvoi, String corps,
			boolean islu) {
		this.id = id;
		this.echange = echange;
		this.ticket = ticket;
		this.utilisateur = utilisateur;
		this.dateEnvoi = dateEnvoi;
		this.corps = corps;
		this.islu = islu;
	}

	public Message(int id, Echange echange, Ticket ticket, Utilisateur utilisateur, Date dateEnvoi, String corps,
			boolean islu, List<Ticket> tickets) {
		this.id = id;
		this.echange = echange;
		this.ticket = ticket;
		this.utilisateur = utilisateur;
		this.dateEnvoi = dateEnvoi;
		this.corps = corps;
		this.islu = islu;
		this.tickets = tickets;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Echange getEchange() {
		return this.echange;
	}

	public void setEchange(Echange echange) {
		this.echange = echange;
	}

	public Ticket getTicket() {
		return this.ticket;
	}

	public void setTicket(Ticket ticket) {
		this.ticket = ticket;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Date getDateEnvoi() {
		return this.dateEnvoi;
	}

	public void setDateEnvoi(Date dateEnvoi) {
		this.dateEnvoi = dateEnvoi;
	}

	public String getCorps() {
		return this.corps;
	}

	public void setCorps(String corps) {
		this.corps = corps;
	}

	public boolean isIslu() {
		return this.islu;
	}

	public void setIslu(boolean islu) {
		this.islu = islu;
	}

	public List<Ticket> getTickets() {
		return this.tickets;
	}

	public void setTickets(List<Ticket> tickets) {
		this.tickets = tickets;
	}

}
