package org.greenlist.entity;
// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Messagepublic generated by hbm2java
 */
@Entity
@Table(name = "messagepublic", catalog = "projet3")
public class Messagepublic implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private int id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPARENT")
	private Messagepublic messageParent;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDOBJET", nullable = false)
	private Objet objet;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_ENVOI", nullable = false, length = 19)
	private Date dateEnvoi;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUtilisateur")
	private Utilisateur utilisateur;
	@Column(name = "MESSAGE", nullable = false, length = 500)
	private String message;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "messageEnfants")
	private List<Messagepublic> messageEnfants = new ArrayList<>();
	
	@Transient
	private boolean root = true;
	@Transient
	private boolean parent = false;	

	public boolean isRoot() {
		return this.getMessageParent().equals(null);
	}
	
	public boolean isParent(){
		if (this.getMessageEnfants() != null){
			return true;
		}
		return false;
	}

	public Messagepublic() {
	}

	public Messagepublic(int id, Objet objet, String message) {
		this.id = id;
		this.objet = objet;
		this.message = message;
	}

	public Messagepublic(int id, Messagepublic messagepublic, Objet objet, Date dateEnvoi, Utilisateur utilisateur,
			String message, List<Messagepublic> messagepublics) {
		super();
		this.id = id;
		this.messageParent = messagepublic;
		this.objet = objet;
		this.dateEnvoi = dateEnvoi;
		this.utilisateur = utilisateur;
		this.message = message;
		this.messageEnfants = messagepublics;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Messagepublic getMessageParent() {
		return messageParent;
	}

	public void setMessageParent(Messagepublic messageParent) {
		this.messageParent = messageParent;
	}

	public Objet getObjet() {
		return objet;
	}

	public void setObjet(Objet objet) {
		this.objet = objet;
	}

	public Date getDateEnvoi() {
		return dateEnvoi;
	}

	public void setDateEnvoi(Date dateEnvoi) {
		this.dateEnvoi = dateEnvoi;
	}

	public Utilisateur getUtilisateur() {
		return utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public List<Messagepublic> getMessageEnfants() {
		return messageEnfants;
	}

	public void setMessageEnfants(List<Messagepublic> messageEnfants) {
		this.messageEnfants = messageEnfants;
	}
	
	

}
