package org.greenlist.entity;
// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Note generated by hbm2java
 */
@Entity
@Table(name = "note", catalog = "projet3")
public class Note implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private int id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDECHANGE", nullable = false)
	private Echange echange;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUTILISATEURNOTE", nullable = false)
	private Utilisateur utilisateurByIdutilisateurnote;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUTILISATEURESTNOTE", nullable = false)
	private Utilisateur utilisateurByIdutilisateurestnote;
	@Column(name = "NOTE", nullable = false)
	private int note;
	@Column(name = "APPRECIATION", length = 500)
	private String appreciation;

	public Note() {
	}

	public Note(int id, Echange echange, Utilisateur utilisateurByIdutilisateurnote,
			Utilisateur utilisateurByIdutilisateurestnote, int note) {
		this.id = id;
		this.echange = echange;
		this.utilisateurByIdutilisateurnote = utilisateurByIdutilisateurnote;
		this.utilisateurByIdutilisateurestnote = utilisateurByIdutilisateurestnote;
		this.note = note;
	}

	public Note(int id, Echange echange, Utilisateur utilisateurByIdutilisateurnote,
			Utilisateur utilisateurByIdutilisateurestnote, int note, String appreciation) {
		this.id = id;
		this.echange = echange;
		this.utilisateurByIdutilisateurnote = utilisateurByIdutilisateurnote;
		this.utilisateurByIdutilisateurestnote = utilisateurByIdutilisateurestnote;
		this.note = note;
		this.appreciation = appreciation;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Echange getEchange() {
		return this.echange;
	}

	public void setEchange(Echange echange) {
		this.echange = echange;
	}

	public Utilisateur getUtilisateurByIdutilisateurnote() {
		return this.utilisateurByIdutilisateurnote;
	}

	public void setUtilisateurByIdutilisateurnote(Utilisateur utilisateurByIdutilisateurnote) {
		this.utilisateurByIdutilisateurnote = utilisateurByIdutilisateurnote;
	}

	public Utilisateur getUtilisateurByIdutilisateurestnote() {
		return this.utilisateurByIdutilisateurestnote;
	}

	public void setUtilisateurByIdutilisateurestnote(Utilisateur utilisateurByIdutilisateurestnote) {
		this.utilisateurByIdutilisateurestnote = utilisateurByIdutilisateurestnote;
	}

	public int getNote() {
		return this.note;
	}

	public void setNote(int note) {
		this.note = note;
	}

	public String getAppreciation() {
		return this.appreciation;
	}

	public void setAppreciation(String appreciation) {
		this.appreciation = appreciation;
	}

}
