package org.greenlist.entity;
// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name = "notification", catalog = "projet3")
public class Notification implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private int id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDTYPE", nullable = false)
	private Typenotification typenotification;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUTILISATEUR", nullable = false)
	private Utilisateur utilisateur;
	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_EMISSION", nullable = false, length = 10)
	private Date dateEmission;
	@Column(name = "ISLU", nullable = false)
	private boolean islu;
	@Column(name = "CONTENU", nullable = false, length = 250)
	private String contenu;

	public Notification() {
	}

	public Notification(int id, Typenotification typenotification, Utilisateur utilisateur, Date dateEmission,
			boolean islu, String contenu) {
		this.id = id;
		this.typenotification = typenotification;
		this.utilisateur = utilisateur;
		this.dateEmission = dateEmission;
		this.islu = islu;
		this.contenu = contenu;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Typenotification getTypenotification() {
		return this.typenotification;
	}

	public void setTypenotification(Typenotification typenotification) {
		this.typenotification = typenotification;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Date getDateEmission() {
		return this.dateEmission;
	}

	public void setDateEmission(Date dateEmission) {
		this.dateEmission = dateEmission;
	}

	public boolean isIslu() {
		return this.islu;
	}

	public void setIslu(boolean islu) {
		this.islu = islu;
	}

	public String getContenu() {
		return this.contenu;
	}

	public void setContenu(String contenu) {
		this.contenu = contenu;
	}

}
