package org.greenlist.entity;
// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Panier generated by hbm2java
 */
@Entity
@Table(name = "panier", catalog = "projet3")
public class Panier implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private int id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUTILISATEUR")
	private Utilisateur utilisateur;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "panier")
	private List<Utilisateur> utilisateurs = new ArrayList<>();
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(	name="OBJET_PANIER",
				joinColumns=@JoinColumn(name="PANIER_ID"),
				inverseJoinColumns=@JoinColumn(name="OBJ_ID"))
	private List<Objet> objets = new ArrayList<>();

	public Panier() {
	}

	public Panier(int id) {
		this.id = id;
	}

	public Panier(int id, Utilisateur utilisateur, List<Utilisateur> utilisateurs, List<Objet> objets) {
		this.id = id;
		this.utilisateur = utilisateur;
		this.utilisateurs = utilisateurs;
		this.objets = objets;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public List<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(List<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	public List<Objet> getObjets() {
		return this.objets;
	}

	public void setObjets(List<Objet> objets) {
		this.objets = objets;
	}

}
