package org.greenlist.entity;
// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Preference generated by hbm2java
 */
@Entity
@Table(name = "preference", catalog = "projet3")
public class Preference implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private int id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDFREQUENCE", nullable = false)
	private FrequenceEmail frequenceEmail;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUTILISATEUR")
	private Utilisateur utilisateur;
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "PREFERENCE_TYPENOTIF", catalog = "projet3", joinColumns = {
			@JoinColumn(name = "IDPREFERENCE", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "IDTYPENOTIF", nullable = false, updatable = false) })
	private List<Typenotification> typenotifications = new ArrayList<>();
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "definit_mail", catalog = "projet3", joinColumns = {
			@JoinColumn(name = "IDPREFERENCE", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "IDTYPEEMAIL", nullable = false, updatable = false) })
	private List<TypeEmail> typeEmails = new ArrayList<>();
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "preference")
	private List<Utilisateur> utilisateurs = new ArrayList<>();

	public Preference() {
	}

	public Preference(int id, FrequenceEmail frequenceEmail) {
		this.id = id;
		this.frequenceEmail = frequenceEmail;
	}

	public Preference(int id, FrequenceEmail frequenceEmail, Utilisateur utilisateur,
			List<Typenotification> typenotifications, List<TypeEmail> typeEmails, List<Utilisateur> utilisateurs) {
		this.id = id;
		this.frequenceEmail = frequenceEmail;
		this.utilisateur = utilisateur;
		this.typenotifications = typenotifications;
		this.typeEmails = typeEmails;
		this.utilisateurs = utilisateurs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public FrequenceEmail getFrequenceEmail() {
		return this.frequenceEmail;
	}

	public void setFrequenceEmail(FrequenceEmail frequenceEmail) {
		this.frequenceEmail = frequenceEmail;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public List<Typenotification> getTypenotifications() {
		return this.typenotifications;
	}

	public void setTypenotifications(List<Typenotification> typenotifications) {
		this.typenotifications = typenotifications;
	}

	public List<TypeEmail> getTypeEmails() {
		return this.typeEmails;
	}

	public void setTypeEmails(List<TypeEmail> typeEmails) {
		this.typeEmails = typeEmails;
	}

	public List<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(List<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
