package org.greenlist.entity;
// Generated 28 avr. 2017 10:03:43 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name = "ticket", catalog = "projet3")
public class Ticket implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private int id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDADMINISTRATEUR")
	private Admin admin;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDMESSAGE")
	private Message message;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDMOTIF", nullable = false)
	private Motifticket motifticket;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDOBJET")
	private Objet objet;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDSOUHAIT")
	private Souhait souhait;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDTYPE", nullable = false)
	private Typeticket typeticket;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUTILISATEURREMONTE", nullable = false)
	private Utilisateur utilisateurByIdutilisateurremonte;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDUTILISATEURSIGNALE")
	private Utilisateur utilisateurByIdutilisateursignale;
	@Column(name = "DESCRIPTION", nullable = false, length = 10000)
	private String description;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATEEMISSION", nullable = false, length = 19)
	private Date dateemission;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATECLOTURE", length = 19)
	private Date datecloture;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ticket")
	private List<Message> messages = new ArrayList<>();

	public Ticket() {
	}

	public Ticket(int id, Motifticket motifticket, Typeticket typeticket, Utilisateur utilisateurByIdutilisateurremonte,
			String description, Date dateemission) {
		this.id = id;
		this.motifticket = motifticket;
		this.typeticket = typeticket;
		this.utilisateurByIdutilisateurremonte = utilisateurByIdutilisateurremonte;
		this.description = description;
		this.dateemission = dateemission;
	}

	public Ticket(int id, Admin admin, Message message, Motifticket motifticket, Objet objet, Souhait souhait,
			Typeticket typeticket, Utilisateur utilisateurByIdutilisateurremonte,
			Utilisateur utilisateurByIdutilisateursignale, String description, Date dateemission, Date datecloture,
			List<Message> messages) {
		this.id = id;
		this.admin = admin;
		this.message = message;
		this.motifticket = motifticket;
		this.objet = objet;
		this.souhait = souhait;
		this.typeticket = typeticket;
		this.utilisateurByIdutilisateurremonte = utilisateurByIdutilisateurremonte;
		this.utilisateurByIdutilisateursignale = utilisateurByIdutilisateursignale;
		this.description = description;
		this.dateemission = dateemission;
		this.datecloture = datecloture;
		this.messages = messages;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

	public Motifticket getMotifticket() {
		return this.motifticket;
	}

	public void setMotifticket(Motifticket motifticket) {
		this.motifticket = motifticket;
	}

	public Objet getObjet() {
		return this.objet;
	}

	public void setObjet(Objet objet) {
		this.objet = objet;
	}

	public Souhait getSouhait() {
		return this.souhait;
	}

	public void setSouhait(Souhait souhait) {
		this.souhait = souhait;
	}

	public Typeticket getTypeticket() {
		return this.typeticket;
	}

	public void setTypeticket(Typeticket typeticket) {
		this.typeticket = typeticket;
	}

	public Utilisateur getUtilisateurByIdutilisateurremonte() {
		return this.utilisateurByIdutilisateurremonte;
	}

	public void setUtilisateurByIdutilisateurremonte(Utilisateur utilisateurByIdutilisateurremonte) {
		this.utilisateurByIdutilisateurremonte = utilisateurByIdutilisateurremonte;
	}

	public Utilisateur getUtilisateurByIdutilisateursignale() {
		return this.utilisateurByIdutilisateursignale;
	}

	public void setUtilisateurByIdutilisateursignale(Utilisateur utilisateurByIdutilisateursignale) {
		this.utilisateurByIdutilisateursignale = utilisateurByIdutilisateursignale;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getDateemission() {
		return this.dateemission;
	}

	public void setDateemission(Date dateemission) {
		this.dateemission = dateemission;
	}

	public Date getDatecloture() {
		return this.datecloture;
	}

	public void setDatecloture(Date datecloture) {
		this.datecloture = datecloture;
	}

	public List<Message> getMessages() {
		return this.messages;
	}

	public void setMessages(List<Message> messages) {
		this.messages = messages;
	}

}
